mytemplates/basicapp/urls.py
from django.urls import path, include
from basicapp import views

# Template tagging
app_name = 'basicapp'

urlpatterns = [
	path('relative/', views.relative, name='relative'),
	path('other/', views.other, name='other'),
]

mytemplates/mytemplates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
	path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls'))
]

mytemplates/basicapp/models.py
from django.db import models

# Create your models here.

mytemplates/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	context_dict = {"text": "hello world", "number" : 100 }
	return render(request, 'basicapp/index.html', context_dict)

def other(request):
	return render(request, 'basicapp/other.html')

def relative(request):
	return render(request, 'basicapp/relative_url_temp.html')

mytemplates/templates/basicapp/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basicapp:other' %}">Other</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

mytemplates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% load custfilters %}

	{% block body_block %}
		<h1> This is my Index.html page!!!</h1>
		<h2> An example of template inheritance! </h2>
		<!-- <h2>{{ text|upper }}</h2> --> <!-- converting the text to upper case -->
		<h2>{{ text|cutout:"hello" }}</h2>
		<h2>{{ number|add:"50" }}</h2> <!-- adding 50 to the number -->
	{% endblock %}

mytemplates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}

	{% block body_block %}
		<h1> This is my Other.html page!!!</h1>
		<h2> An example of template inheritance! </h2>
	{% endblock %}

mytemplates/templates/basicapp/relative_url_temp.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>RelativeURL</title>
</head>
<body>
	<h1>This is my Relative URL Templates Page!!</h1>
	<a href="{% url 'basicapp:other' %}">The Other Page</a>
	<br>
	<a href="{% url 'admin:index' %}">The Admin Page</a>
	<br>
	<a href="{% url 'index' %}">The Index Page</a>

</body>
</html>